package com.game.characters;

public class GiantRat extends Monsters {
    private final String name = "Giant rat";
    private int hp = 100;
    // energy: get auto-generated by 10 after each round
    private int energy = 100;
    private int attack = 10;

    public void lickTheWound() {
        if (energy >= 30) {
            hp = hp + 10;
            energy = energy - 30;
        } else {
            System.out.println("Failed...The Giant rat has run out of energy...");
        }
    }

    @Override
    public void useSpecialAbility() {
        lickTheWound();
    }

    @Override
    public String getName() {
        return name;
    }
}