package com.game.characters;

class SkeletonKnight extends Monsters{
    private final String name = "SkeletonKight";
    private int hp = 150;
    // rage: get generated by 10 with getting attacked
    private int rage = 10;
    private int attack = 10;

    // skills
    void fear() {
        if (rage >= 5) {
            hp += 10;
            rage -= 15;
        }
    }
}