package com.game.characters;

class SkeletonKnight extends Monsters{
    private final String name = "SkeletonKnight";
    // rage: get generated by 10 with getting attacked
    private int rage = 10;
    private int skeletonKightHp = getMonsterHP();

    // skills
    void fear() {
        if (rage >= 5) {
            skeletonKightHp += 10;
            rage -= 15;
        }
    }

    void femurStab() {
        if (rage >= 5) {
            skeletonKightHp += 30;
            rage -= 20;
        }
    }

    @Override
    public void useSpecialAbility(){

    }

    public int getRage() {
        return rage;
    }

    public void setRage(int rage) {
        this.rage = rage;
    }

    @Override
    public String getName() {
        return name;
    }
}